# Generated by Django 4.2.6 on 2023-10-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekonomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=150)),
                ('aciklama', models.TextField()),
                ('eklenme_tarihi', models.DateField()),
                ('video', models.TextField()),
                ('eklenme_tarih', models.DateTimeField(auto_now_add=True)),
                ('kapak', models.CharField(max_length=200)),
                ('kaynak', models.CharField(max_length=200)),
                ('ulke', models.CharField(max_length=150)),
                ('kategori', models.ManyToManyField(to='videolar.kategoriler')),
            ],
            options={
                'verbose_name': 'Ekonomi',
                'verbose_name_plural': 'Ekonomi',
            },
        ),
    ]
