# Generated by Django 4.2.6 on 2023-10-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videolar', '0002_ekonomi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ekonomi',
            new_name='Haberler',
        ),
        migrations.AlterModelOptions(
            name='haberler',
            options={'verbose_name': 'Haberler', 'verbose_name_plural': 'Haberler'},
        ),
    ]
