# Generated by Django 4.2.6 on 2023-10-29 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videolar', '0004_ekonomi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ekonomi',
            name='eklenme_tarih',
        ),
        migrations.CreateModel(
            name='Spor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=120)),
                ('sira', models.IntegerField()),
                ('tarih', models.DateField()),
                ('Ekonomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videolar.ekonomi')),
            ],
            options={
                'verbose_name': 'Spor',
                'verbose_name_plural': 'Spor',
            },
        ),
    ]
