# Generated by Django 4.2.6 on 2023-10-29 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videolar', '0005_remove_ekonomi_eklenme_tarih_spor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gündem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=200)),
                ('sira', models.IntegerField()),
                ('tarih', models.DateField()),
                ('eklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('video', models.TextField()),
                ('video2', models.TextField(default='')),
                ('aciklama', models.TextField()),
                ('Spor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videolar.spor')),
            ],
            options={
                'verbose_name': 'Gündem',
                'verbose_name_plural': 'Gündem',
            },
        ),
    ]
