# Generated by Django 4.2.6 on 2023-10-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videolar', '0006_gündem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spor',
            new_name='Sondakika',
        ),
        migrations.AlterModelOptions(
            name='sondakika',
            options={'verbose_name': 'Sondakika', 'verbose_name_plural': 'Son Dakika'},
        ),
        migrations.RemoveField(
            model_name='gündem',
            name='Spor',
        ),
    ]
